### ISSUE TITLE
자습실을 볼 때에 상 하단이 잘려서 보여요

### ISSUE THREAD

**Issue by kimdaehee0824** [DSM-FLOW/DMS-iOS#209]
### Describe

언젠가는 고쳐주세요

### Additional

![스크린샷 2023-03-07 오전 10 01 02](https://user-images.githubusercontent.com/68860610/223292028-7bebf900-1541-40ab-a527-57397534c6e1.png)

**Comment by winwx** [comment]
실수로 main에 푸쉬 해서 닫습니다 ㅎㅎ..
